name: BMI CI

env:
  AZURE_WEBAPP_NAME: a00086200-bmi2026
  AZURE_WEBAPP_PACKAGE_PATH: publish/myapp

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore bmi2024.sln

      - name: Build for Release
        run: dotnet build bmi2024.sln --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: dotnet test bmiUnitTestProject/bmiUnitTestProject.csproj --configuration Release --no-build --settings bmiUnitTestProject/coverlet.runsettings --collect "XPlat Code Coverage" --logger trx

      - name: Publish unit test results
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: MS Tests
          path: '**/*.trx'
          reporter: dotnet-trx

      - name: Publish application
        run: dotnet publish bmi2021/bmi2026.csproj --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

